server:
  port: 9001


#  ˝æ›‘¥≈‰÷√
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: '0407'

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
